swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /cart:
    get:
      operationId: cart.readAllCarts
      tags:
        - Cart
      summary: Read the entire list of carts
      description: Read the list of Cart
      responses:
        200:
          description: Successfully read cart list operation
          schema:
            type: object
            properties:
              id:
                type: string
                description: id of the item.
              Nom:
                type: string
                description: name of the buyer.
              Prix:
                type: string
                description: price.
              Commentary:
                type: array
              Description:
                type: array

  /cart/post:
    post:
      operationId: cart.addItem
      tags:
      - Cart
      summary: Add a new item.
      parameters:
      - name: newItem
        in: body
        required: true
        description: Name of the cart to add
        schema:
          type: object
          properties:
            id:
              type: string
              description: id of the item.
            Nom:
              type: string
              description: name of the buyer.
            Prix:
              type: string
              description: price.
            Commentary:
              type: array
            Description:
              type: array
      responses:
        200:
          description: Successfully added cart to dictionary.

  /cart/{nameOfCart}:
    get:
      operationId: cart.readOneCart
      tags:
        - Cart
      summary: Read content of only one card
      parameters:
      - name: nameOfCart
        in: path
        type: string
        description: Name of the cart to read
        required: true
      responses:
        200:
          description: Successfully read cart list operation
          schema:
            type: object
            properties:
              id:
                type: string
                description: id of the item.
              Nom:
                type: string
                description: name of the buyer.
              Prix:
                type: string
                description: price.
              Commentary:
                type: array
              Description:
                type: array

  /cart/delete/{nameOfCart}:
    delete:
      operationId: cart.deleteCart
      tags:
        - Cart
      summary: Delete cart according to its name
      parameters:
      - name: nameOfCart
        in: path
        type: string
        description: Name of the cart to suppress
        required: true
      responses:
        200:
          description: Successfully suppresed cart from dictionary

  /cart/{nameOfCart}/item/delete/{id}:
    delete:
      operationId: cart.deleteItem
      tags:
        - Cart
      summary: delete an item of a cart.
      parameters:
        - name: nameOfCart
          in: path
          type: string
          required: true
          description: Name of the cart in which the item is suppressed.
        - name: id
          in: path
          type: string
          required: true
          description: Name of the item that's being suppressed.
      responses:
        200:
          description: Successfully suppressed item from cart.





