swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /cart:
    get:
      operationId: cart.readAllCarts
      tags:
        - Cart
      summary: Read the entire list of carts
      description: Read the list of Cart
      parameters:
      - name: length
        in: query
        type: integer
        description: Number of people to get from people
        required: false
      - name: offset
        in: query
        type: integer
        description: Offset from beginning of list where to start gathering people
        required: false
      responses:
        200:
          description: Successfully read cart list operation
          schema:
            type: array
            items:
              properties:
                fname:
                  type: string
                lname:
                  type: string

  /cart/{nameOfCart}:
    get:
      operationId: cart.readOneCart
      tags:
        - Cart
      summary: Read content of only one card
      parameters:
      - name: nameOfCart
        in: path
        type: string
        description: Name of the cart to read
        required: true
      responses:
        200:
          description: Successfully read cart list operation
          schema:
            properties:
              fname:
                type: string
              lname:
                type: string

  /cart/delete/{nameOfCart}:
    delete:
      operationId: cart.deleteCart
      tags:
        - Cart
      summary: Delete cart according to its name
      parameters:
      - name: nameOfCart
        in: path
        type: string
        description: Name of the cart to suppress
        required: true

      responses:
        200:
          description: Successfully suppresed cart from dictionary

  /cart/post:
    post:
      operationId: cart.addCart
      tags:
        - Cart
      summary: Add a new cart for new user.
      parameters:
      - name: newCart
        in: body
        required: true
        description: Name of the cart to add
        schema:
          type: object
          properties:
            id:
              type: string
              description: id of the item.
            Nom:
              type: string
              description: name of the buyer.
            Prix:
              type: string
              description: price.
            Commentary:
              type: array
            Description:
              type: array

      responses:
        200:
          description: Successfully added cart to dictionary





