swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /cart:
    get:
      operationId: cart.readAllItems
      tags:
        - Cart
      summary: Read the entire list of carts
      description: Read the list of Cart
      parameters:
      - name: length
        in: query
        type: integer
        description: Number of people to get from people
        required: false
      - name: offset
        in: query
        type: integer
        description: Offset from beginning of list where to start gathering people
        required: false
      responses:
        200:
          description: Successfully read cart list operation
          schema:
            type: array
            items:
              properties:
                Id:
                  type: string
                Nom:
                  type: string
                Prix:
                  type: string
                Commentaire:
                  type: list
                Description:
                  type: list
  /oneCart:
    get:
      operationId: cart.giveToken
      tags:
        - Cart
      summary: Read content of only one card
      parameters:
#      - name: length
#        in: query
#        type: integer
#        description: Number of people to get from people
#        required: false
      - nameOfCart: string
        in: query
        type: integer
        description: Name of cart
        required: false
      responses:
        200:
          description: Successfully read cart list operation
          schema:
            type: array
            items:
              properties:
                Id:
                  type: string
                Nom:
                  type: string
                Prix:
                  type: string
                Commentaire:
                  type: list
                Description:
                  type: list